// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package com.mairuis.raft.proto;

public final class Raft {
  private Raft() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VoteOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.mairuis.raft.proto.Vote)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *所在周期
     * </pre>
     *
     * <code>int32 term = 1;</code>
     * @return The term.
     */
    int getTerm();

    /**
     * <pre>
     *投给那个实例
     * </pre>
     *
     * <code>int32 serverId = 2;</code>
     * @return The serverId.
     */
    int getServerId();

    /**
     * <pre>
     *最大事务Id
     * </pre>
     *
     * <code>int32 txnId = 3;</code>
     * @return The txnId.
     */
    int getTxnId();
  }
  /**
   * Protobuf type {@code com.mairuis.raft.proto.Vote}
   */
  public static final class Vote extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.mairuis.raft.proto.Vote)
      VoteOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Vote.newBuilder() to construct.
    private Vote(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Vote() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Vote();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Vote(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              term_ = input.readInt32();
              break;
            }
            case 16: {

              serverId_ = input.readInt32();
              break;
            }
            case 24: {

              txnId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mairuis.raft.proto.Raft.internal_static_com_mairuis_raft_proto_Vote_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mairuis.raft.proto.Raft.internal_static_com_mairuis_raft_proto_Vote_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mairuis.raft.proto.Raft.Vote.class, com.mairuis.raft.proto.Raft.Vote.Builder.class);
    }

    public static final int TERM_FIELD_NUMBER = 1;
    private int term_;
    /**
     * <pre>
     *所在周期
     * </pre>
     *
     * <code>int32 term = 1;</code>
     * @return The term.
     */
    @java.lang.Override
    public int getTerm() {
      return term_;
    }

    public static final int SERVERID_FIELD_NUMBER = 2;
    private int serverId_;
    /**
     * <pre>
     *投给那个实例
     * </pre>
     *
     * <code>int32 serverId = 2;</code>
     * @return The serverId.
     */
    @java.lang.Override
    public int getServerId() {
      return serverId_;
    }

    public static final int TXNID_FIELD_NUMBER = 3;
    private int txnId_;
    /**
     * <pre>
     *最大事务Id
     * </pre>
     *
     * <code>int32 txnId = 3;</code>
     * @return The txnId.
     */
    @java.lang.Override
    public int getTxnId() {
      return txnId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (term_ != 0) {
        output.writeInt32(1, term_);
      }
      if (serverId_ != 0) {
        output.writeInt32(2, serverId_);
      }
      if (txnId_ != 0) {
        output.writeInt32(3, txnId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (term_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, term_);
      }
      if (serverId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, serverId_);
      }
      if (txnId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, txnId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mairuis.raft.proto.Raft.Vote)) {
        return super.equals(obj);
      }
      com.mairuis.raft.proto.Raft.Vote other = (com.mairuis.raft.proto.Raft.Vote) obj;

      if (getTerm()
          != other.getTerm()) return false;
      if (getServerId()
          != other.getServerId()) return false;
      if (getTxnId()
          != other.getTxnId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TERM_FIELD_NUMBER;
      hash = (53 * hash) + getTerm();
      hash = (37 * hash) + SERVERID_FIELD_NUMBER;
      hash = (53 * hash) + getServerId();
      hash = (37 * hash) + TXNID_FIELD_NUMBER;
      hash = (53 * hash) + getTxnId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mairuis.raft.proto.Raft.Vote parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mairuis.raft.proto.Raft.Vote parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mairuis.raft.proto.Raft.Vote parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mairuis.raft.proto.Raft.Vote parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mairuis.raft.proto.Raft.Vote parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mairuis.raft.proto.Raft.Vote parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mairuis.raft.proto.Raft.Vote parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mairuis.raft.proto.Raft.Vote parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mairuis.raft.proto.Raft.Vote parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mairuis.raft.proto.Raft.Vote parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mairuis.raft.proto.Raft.Vote parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mairuis.raft.proto.Raft.Vote parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mairuis.raft.proto.Raft.Vote prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mairuis.raft.proto.Vote}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.mairuis.raft.proto.Vote)
        com.mairuis.raft.proto.Raft.VoteOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mairuis.raft.proto.Raft.internal_static_com_mairuis_raft_proto_Vote_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mairuis.raft.proto.Raft.internal_static_com_mairuis_raft_proto_Vote_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mairuis.raft.proto.Raft.Vote.class, com.mairuis.raft.proto.Raft.Vote.Builder.class);
      }

      // Construct using com.mairuis.raft.proto.Raft.Vote.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        term_ = 0;

        serverId_ = 0;

        txnId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mairuis.raft.proto.Raft.internal_static_com_mairuis_raft_proto_Vote_descriptor;
      }

      @java.lang.Override
      public com.mairuis.raft.proto.Raft.Vote getDefaultInstanceForType() {
        return com.mairuis.raft.proto.Raft.Vote.getDefaultInstance();
      }

      @java.lang.Override
      public com.mairuis.raft.proto.Raft.Vote build() {
        com.mairuis.raft.proto.Raft.Vote result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.mairuis.raft.proto.Raft.Vote buildPartial() {
        com.mairuis.raft.proto.Raft.Vote result = new com.mairuis.raft.proto.Raft.Vote(this);
        result.term_ = term_;
        result.serverId_ = serverId_;
        result.txnId_ = txnId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mairuis.raft.proto.Raft.Vote) {
          return mergeFrom((com.mairuis.raft.proto.Raft.Vote)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mairuis.raft.proto.Raft.Vote other) {
        if (other == com.mairuis.raft.proto.Raft.Vote.getDefaultInstance()) return this;
        if (other.getTerm() != 0) {
          setTerm(other.getTerm());
        }
        if (other.getServerId() != 0) {
          setServerId(other.getServerId());
        }
        if (other.getTxnId() != 0) {
          setTxnId(other.getTxnId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mairuis.raft.proto.Raft.Vote parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mairuis.raft.proto.Raft.Vote) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int term_ ;
      /**
       * <pre>
       *所在周期
       * </pre>
       *
       * <code>int32 term = 1;</code>
       * @return The term.
       */
      @java.lang.Override
      public int getTerm() {
        return term_;
      }
      /**
       * <pre>
       *所在周期
       * </pre>
       *
       * <code>int32 term = 1;</code>
       * @param value The term to set.
       * @return This builder for chaining.
       */
      public Builder setTerm(int value) {
        
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *所在周期
       * </pre>
       *
       * <code>int32 term = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTerm() {
        
        term_ = 0;
        onChanged();
        return this;
      }

      private int serverId_ ;
      /**
       * <pre>
       *投给那个实例
       * </pre>
       *
       * <code>int32 serverId = 2;</code>
       * @return The serverId.
       */
      @java.lang.Override
      public int getServerId() {
        return serverId_;
      }
      /**
       * <pre>
       *投给那个实例
       * </pre>
       *
       * <code>int32 serverId = 2;</code>
       * @param value The serverId to set.
       * @return This builder for chaining.
       */
      public Builder setServerId(int value) {
        
        serverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *投给那个实例
       * </pre>
       *
       * <code>int32 serverId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerId() {
        
        serverId_ = 0;
        onChanged();
        return this;
      }

      private int txnId_ ;
      /**
       * <pre>
       *最大事务Id
       * </pre>
       *
       * <code>int32 txnId = 3;</code>
       * @return The txnId.
       */
      @java.lang.Override
      public int getTxnId() {
        return txnId_;
      }
      /**
       * <pre>
       *最大事务Id
       * </pre>
       *
       * <code>int32 txnId = 3;</code>
       * @param value The txnId to set.
       * @return This builder for chaining.
       */
      public Builder setTxnId(int value) {
        
        txnId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *最大事务Id
       * </pre>
       *
       * <code>int32 txnId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTxnId() {
        
        txnId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.mairuis.raft.proto.Vote)
    }

    // @@protoc_insertion_point(class_scope:com.mairuis.raft.proto.Vote)
    private static final com.mairuis.raft.proto.Raft.Vote DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mairuis.raft.proto.Raft.Vote();
    }

    public static com.mairuis.raft.proto.Raft.Vote getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Vote>
        PARSER = new com.google.protobuf.AbstractParser<Vote>() {
      @java.lang.Override
      public Vote parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Vote(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Vote> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Vote> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.mairuis.raft.proto.Raft.Vote getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mairuis_raft_proto_Vote_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mairuis_raft_proto_Vote_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nraft.proto\022\026com.mairuis.raft.proto\"5\n\004" +
      "Vote\022\014\n\004term\030\001 \001(\005\022\020\n\010serverId\030\002 \001(\005\022\r\n\005" +
      "txnId\030\003 \001(\0052N\n\004Peer\022F\n\006VoteTo\022\034.com.mair" +
      "uis.raft.proto.Vote\032\034.com.mairuis.raft.p" +
      "roto.Vote\"\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_mairuis_raft_proto_Vote_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_mairuis_raft_proto_Vote_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mairuis_raft_proto_Vote_descriptor,
        new java.lang.String[] { "Term", "ServerId", "TxnId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
